addSbtPlugin("com.eed3si9n"          % "sbt-assembly"          % "0.14.9")
addSbtPlugin("com.eed3si9n"          % "sbt-buildinfo"         % "0.9.0")
addSbtPlugin("com.typesafe.sbt"      % "sbt-git"               % "1.0.0")
addSbtPlugin("com.typesafe.sbt"      % "sbt-native-packager"   % "1.7.5")
addSbtPlugin("se.marcuslonnberg"     % "sbt-docker"            % "1.8.0")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"          % "2.0.2")
addSbtPlugin("org.scalastyle"       %% "scalastyle-sbt-plugin" % "1.0.0")
